<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>MockBoard Session</title>

    <link href="/css/bootstrap-4.5.3.min.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
</head>
<body>
<h1>MockBoard Session</h1>



<script src="/js/jquery-3.5.1.slim.min.js"></script>
<script src="/js/bootstrap-4.5.3.bundle.min.js"></script>
<script src="/js/app.js"></script>
</body>
</html>