<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>MockBoard | The Instant API Mock Server & Webhook Tester</title>
    <meta name="description" content="Generate instant fake HTTP endpoints for development. MockBoard is a free, no-login API simulator for frontend testing, webhooks, and prototyping.">
    <meta name="keywords" content="api mock, fake backend, http simulator, webhook tester, json generator, dev tools, api simulation, rest api mock">

    <meta property="og:type" content="website">
    <meta property="og:title" content="MockBoard - Instant FakeEnd">
    <meta property="og:description" content="Stop waiting for the backend. Mock APIs in seconds.">

    <link href="/css/bootstrap-4.5.3.min.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">

    <script type="application/ld+json">
        {
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            "name": "MockBoard",
            "applicationCategory": "DeveloperTool",
            "offers": { "@type": "Offer", "price": "0" }
        }
    </script>
</head>
<body>
<h1>MockBoard Landing</h1>

<script src="/js/jquery-3.5.1.slim.min.js"></script>
<script src="/js/bootstrap-4.5.3.bundle.min.js"></script>
</body>
</html>